### PR TITLE
change shell scipt mode to fix pipeline

### PR DESCRIPTION
**Pull request by raghavendra-nataraj**

### CODE REVIEW

**Comment by JocelynBerrendonner** [comment]
I am curious... What is this change?

**Comment by raghavendra-nataraj** [comment]
The file mode is changed to executable. It was not a executable earlier

**Comment by JocelynBerrendonner** [comment]
Thanks! This is odd. The script used to work before. I guess the mode was changed to non executable during the repository split... Thanks for fixing it!

**Review by JocelynBerrendonner — APPROVED** [review]
LGTM

**Comment by raghavendra-nataraj** [comment]
Thanks

**Pull request merged**
